version: 0.2
env:
  secret-manger:
    
phases:

  install:
    runtime-versions:
      nodejs: 14
    commands:
      - export NODE_OPTIONS="--max-old-space-size=8192"
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - echo Installing
      - npm install
      
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install -g serverless
  build:
    commands:
  
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - npm run prod-build
  post_build:
    commands:
      - echo post build completed on `date`